#!/bin/sh
rpm -ivh cyrus-sasl-2.1.15-10.i386.rpm 
rpm -ivh cyrus-sasl-md5-2.1.15-10.i386.rpm 
rpm -ivh krb5-workstation-1.2.7-47.i386.rpm 
rpm -ivh krbafs-1.1.1-11.i386.rpm 
rpm -ivh openldap-2.0.27-17.i386.rpm 
rpm -ivh openldap-clients-2.0.27-17.i386.rpm 
rpm -ivh pam_krb5-1.77-1.i386.rpm 

mkdir -p /var/kerberos/krb5kdc
mkdir -p /usr/LDAP
mkdir -p /usr/LDAP/Member
mkdir -p /usr/LDAP/Member/New
mkdir -p /usr/LDAP/Member/Old

