# HP ProLiant Support software input file
#
# If you wish to have a custom configuration of System Management 
# passwords or SNMP, modify the values and/or uncomment the lines below.  
# Changing the values here can be useful in deploying multiple servers 
# with the same custom configuration.

export CMASILENT="YES"

# export CMALOCALHOSTRWCOMMSTR - SNMP read/write community string for local
#  host access.
#  ex. export CMALOCALHOSTRWCOMMSTR=private
# export CMALOCALHOSTROCOMMSTR - SNMP read-only community string for local host
#  access.
#  ex. export CMALOCALHOSTROCOMMSTR=public
export CMALOCALHOSTRWCOMMSTR=08281953B
export CMALOCALHOSTROCOMMSTR=08281953B

# export CMAMGMTSTATIONRWIPORDNS - IP address or DNS host name of a system with 
#  read/write access to server as a management station.  Multiple 
#  locations may be specified, separated by a space.
#  ex. export CMAMGMTSTATIONRWIPORDNS=192.168.1.1
# export CMAMGMTSTATIONRWCOMMSTR - SNMP read/write community string for a system 
#  with read/write access that serves as a management station.  Multiple 
#  strings may be specified, separated by a space.
#  ex. export CMAMGMTSTATIONRWCOMMSTR=private
export CMAMGMTSTATIONRWIPORDNS=FH2K190.fhmis.net
export CMAMGMTSTATIONRWIPORDNS=nagios02.floridahospital.org
export CMAMGMTSTATIONRWIPORDNS=cacti02.floridahospital.org
export CMAMGMTSTATIONRWCOMMSTR=08281953B
# export CMAMGMTSTATIONROIPORDNS - IP address or DNS host name of a system with 
#  read-only access to server as a management station.  Multiple 
#  locations may be specified, separated by a space.
#  ex. export CMAMGMTSTATIONROIPORDNS=192.168.1.1
# export CMAMGMTSTATIONROCOMMSTR - SNMP read/write community string for a system 
#  with read-only access that serves as a management station.  Multiple 
#  strings may be specified, separated by a space.
#  ex. export CMAMGMTSTATIONROCOMMSTR=private
#export CMAMGMTSTATIONROIPORDNS=
#export CMAMGMTSTATIONROCOMMSTR=

# export CMADEFTRAPCOMMSTR - Default SNMP community string for traps.
#  ex. export CMADEFTRAPCOMMSTR=private
# export CMATRAPDESTINATIONCOMMSTR - SNMP destination trap community string.
#  ex. export CMATRAPDESTINATIONCOMMSTR=private
# export CMATRAPDESTINATIONIPORDNS - IP address or DNS hostname of a server to 
#  send SNMP traps.
#  ex. export CMATRAPDESTINATIONIPORDNS=10.0.0.1
#export CMADEFTRAPCOMMSTR=
#export CMATRAPDESTINATIONCOMMSTR=
#export CMATRAPDESTINATIONIPORDNS=

# export CMASYSCONTACT & export CMASYSLOCATION - System contact and location information
#  Must be in double quotes if contains spaces.
#  ex. export CMASYSCONTACT="Joe Smith"
#  ex. export CMASYSLOCATION="1234 Smith Lane, Building Admin #5"
#export CMASYSCONTACT=
#export CMASYSLOCATION=

# export CMAAGENTEXCLUDESTR - Agent exclusion on startup
# ex. export CMAAGENTEXCLUDESTR="cmaeventd cmaperfd"
#export CMAAGENTEXCLUDESTR=

# Do you want to enable the VMware-SNMP sub-agent
# N = No
# Y = Yes
export ENABLEVMSNMP=Y

# Do you want to enable SNMP traps for virtual machine events
# N = No
# Y = Yes
export ENABLEVMTRAPS=Y

# Do No Edit This Value
export SNMPCONFLOC=1

# The following two variables are needed only for ESX 3.0.x systems. You
# don't need to configure these two variables on ESX 2.5.x systems
 
# For accessing the System Management Homepage, the port for hpim service 
# (2381) should be enabled in the firewall. Default is to enable this port. 
# Set export ENABLEHPIMPORT=N if you don't want to enable the port for hpim 
# service
# N = No
# Y = Yes
export ENABLEHPIMPORT=Y
 
# For the Insight Manager agents to communicate properly with HP Systems 
# Insight Manager, the snmpd service should be enabled in the firewall. 
# Default is to enable this service.
# Set export ENABLESNMPSERVICE=N if you don't want to enable snmpd service
# N = No
# Y = Yes
export ENABLESNMPSERVICE=Y
