[logging]
 default = FILE:/var/log/krb5libs.log
 kdc = FILE:/var/log/krb5kdc.log
 admin_server = FILE:/var/log/kadmind.log

[libdefaults]
 ticket_lifetime = 24000
 default_realm = FLHOSP.NET
 dns_lookup_realm = true
 dns_lookup_kdc = true
 default_tkt_enctypes = des-cbc-crc des-cbc-md5
 default_tgs_enctypes = des-cbc-crc

[realms]
 FLHOSP.NET = {
  kdc = FLHOSP.NET:88
  admin_server = FLHOSP.NET:464
  default_domain = flhosp.net
 }

[domain_realm]
 .flhosp.net = FLHOSP.NET
 flhosp.net = FLHOSP.NET

[kdc]
 profile = /var/kerberos/krb5kdc/kdc.conf

[pam]
 debug = false
 ticket_lifetime = 36000
 renew_lifetime = 36000
 forwardable = true
 krb4_convert = false
