# To opt out of the system crypto-policies configuration of krb5, remove the
# symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
includedir /etc/krb5.conf.d/

[logging]
    default = FILE:/var/log/krb5libs.log
    kdc = FILE:/var/log/krb5kdc.log
    admin_server = FILE:/var/log/kadmind.log

[libdefaults]
  default_realm = {{ domain | upper }}
  default_ccache_name = KEYRING:persistent:%{uid}
  default_tgs_enctypes = AES256-CTS AES128-CTS RC4-HMAC
  default_tkt_enctypes = AES256-CTS AES128-CTS RC4-HMAC
  preferred_enctypes = AES256-CTS AES128-CTS RC4-HMAC
  dns_lookup_kdc = true
  dns_lookup_realm = true
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true
  rdns = false
  spake_preauth_groups = edwards25519
  dns_canonicalize_hostname = fallback
  qualify_shortname = ""
  udp_preference_limit = 0
  pkinit_kdc_hostname = <DNS>
  pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
  pkinit_cert_match = <EKU>msScLogin
  pkinit_eku_checking = kpServerAuth
  pkinit_win2k_require_binding = false
  pkinit_identities = PKCS11:/opt/likewise/lib64/libpkcs11wrapper.so

[domain_realm]
  .central.nyced.org = CENTRAL.NYCED.ORG
  .qa.appdev = QA.APPDEV
  .cstg.nstg.local = CSTG.NSTG.LOCAL
  .ows.test.lab = OWS.TEST.LAB
  .nyced.org = NYCED.ORG
  .systems.schools.nyc = SYSTEMS.SCHOOLS.NYC
  .opt.osss.local = OPT.OSSS.LOCAL
  .dsf.osss.local = DSF.OSSS.LOCAL
  .osfns.osss.local = OSFNS.OSSS.LOCAL
  .mynycschools.org = MYNYCSCHOOLS.ORG
  .nycedext.org = NYCEDEXT.ORG
  .finance360.net = FINANCE360.NET
[realms]
  {{ domain | upper }} = {
   auth_to_local = RULE:[1:$0\$1](^CENTRAL\.NYCED\.ORG\\.*)s/^CENTRAL\.NYCED\.ORG/CENTRAL/
   auth_to_local = RULE:[1:$0\$1](^CENTRAL\.NYCED\.ORG\\.*)s/^CENTRAL\.NYCED\.ORG/CENTRAL/
   auth_to_local = RULE:[1:$0\$1](^NYCED\.ORG\\.*)s/^NYCED\.ORG/NYCED/
   auth_to_local = RULE:[1:$0\$1](^SYSTEMS\.SCHOOLS\.NYC\\.*)s/^SYSTEMS\.SCHOOLS\.NYC/SYSTEMS/
   auth_to_local = RULE:[1:$0\$1](^OPT\.OSSS\.LOCAL\\.*)s/^OPT\.OSSS\.LOCAL/PUPIL_TRANSPORT/
   auth_to_local = RULE:[1:$0\$1](^DSF\.OSSS\.LOCAL\\.*)s/^DSF\.OSSS\.LOCAL/DSFNT4/
   auth_to_local = RULE:[1:$0\$1](^OSFNS\.OSSS\.LOCAL\\.*)s/^OSFNS\.OSSS\.LOCAL/FOODSERVER/
   auth_to_local = RULE:[1:$0\$1](^MYNYCSCHOOLS\.ORG\\.*)s/^MYNYCSCHOOLS\.ORG/MYNYCSCHOOLS/
   auth_to_local = RULE:[1:$0\$1](^NYCEDEXT\.ORG\\.*)s/^NYCEDEXT\.ORG/NYCEDEXT/
   auth_to_local = RULE:[1:$0\$1](^FINANCE360\.NET\\.*)s/^FINANCE360\.NET/FINANCE360/
   auth_to_local = DEFAULT
  }
[appdefaults]
  pam = {
   mappings = {{ cname }}\\(.*) $1@{{ domain | upper }}
   forwardable = true
   validate = true
  }

