acl_file = /var/kerberos/krb5kdc/kadm5.acl
dict_file = /usr/share/dict/words
admin_keytab = /var/kerberos/krb5kdc/kadm5.keytab
v4_mode = nopreauth

[realms]
 FLHOSP.NET = {
  master_key_type = des-cbc-crc
  supported_enctypes = des3-cbc-raw:normal des3-cbc-raw:norealm
                       des3-cbc-raw:onlyrealm des3-cbc-sha1:normal
                       des3-cbc-sha1:norelam des3-cbc-sha1:onlyrelam
                       des-cbc-crc:v4 des-cbc-crc:afs3
                       des-cbc-crc:normal des-cbc-crc:norealm
                       des-cbc-crc:onlyrealm des-cbc-md4:v4
                       des-cbc-md4:afs3 des-cbc-md4:normal
                       des-cbc-md4:norealm des-cbc-md4:onlyrealm
                       des-cbc-md5:v4 des-cbc-md5:afs3
                       des-cbc-md5:normal des-cbc-md5:norealm
                       des-cbc-md5:onlyrealm des-cbc-raw:v4
                       des-cbc-raw:afs3 des-cbc-raw:normal
                       des-cbc-raw:norealm des-cbc-raw:onlyrealm
                       des-cbc-sha1:v4 des-cbc-sha1:afs3
                       des-cbc-sha1:normal des-cbc-sha1:norealm
                       des-cbc-sha1:onlyrealm
}
